### PR TITLE
 Overlay of Codeutsava 8.0 and the enter button

### PR DESCRIPTION
**Pull request by karanmanglani**
I have successfully created the reveal animation as per the instructions provided. I utilized a stock GIF of ground breaking since I was unable to find an exact match that incorporated our logo seamlessly. The result can be viewed here :- 

https://github.com/user-attachments/assets/bf0d66ed-40ae-45d4-983d-dd5b823582fa

I am open to any suggestions for improvement and would appreciate your feedback.

### CODE REVIEW

**Comment by karanmanglani** [comment]
Sir i have also included the gif in the commit but it seems like it does not gets loaded as an asset on netlify preview. I am confused as so why is it happening , the gif is being loaded locally but not on the netlify preview.

**Comment by rishabhpathak359** [comment]
> Sir i have also included the gif in the commit but it seems like it does not gets loaded as an asset on netlify preview. I am confused as so why is it happening , the gif is being loaded locally but not on the netlify preview.
  
  gif wala part shayad comment out kr rkha aapne

**Comment by karanmanglani** [comment]
Sir wo mene comment out kr rkha as pehle m uski positikning k liye rkha hua tha baad m mene js s insert ki h image at certain time for animation.

**Comment by rishabhpathak359** [comment]
> Sir wo mene comment out kr rkha as pehle m uski positikning k liye rkha hua tha baad m mene js s insert ki h image at certain time for animation.

then ig wo file build output mein generate nii ho rhi hogi maybe public folder mein add krke try krna.

**Comment by karanmanglani** [comment]
Ok sir

**Pull request closed without merging**
